### ISSUE TITLE
Frames validation

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/validation#22]
Frames validation has been a long discussion topic and several issues within official poliastro repository have been opened about it, see:

* Planetary frames validation: https://github.com/poliastro/poliastro/issues/109
* Planetary frames velocity transformations: https://github.com/poliastro/poliastro/issues/451

At the moment, all poliastro source code related to frames is located within the [frames sub-package](https://github.com/poliastro/poliastro/tree/master/src/poliastro/frames). On the other hand, Orekit documentation about frames is collected in the following links:

*  Orekit Frames architecture: https://www.orekit.org/site-orekit-10.3/architecture/frames.html
* Orekit frames tutorial (Java API): https://www.orekit.org/site-orekit-tutorials-10.3/tutorials/frames.html
* Orekit frames example (Python wrapper): https://gitlab.orekit.org/orekit-labs/python-wrapper/-/blob/master/examples/Frames_and_Coordinate_Systems.ipynb

Finally, official IAU documentation about *Cartographic Coordinates and Rotational Elements* is depicted in the following webpage: https://astrogeology.usgs.gov/groups/IAU-WGCCRE

**Comment by jorgepiloto** [comment]
More useful links about how GMAT manages representations of body inertial and body fixed representations:

* GMAT coordinate systems: http://gmat.sourceforge.net/docs/R2018a/html/CoordinateSystem.html
* GMAT celestial body orientation models: http://gmat.sourceforge.net/docs/R2018a/html/CelestialBody.html#CelestialBody_Remarks

**Comment by jorgepiloto** [comment]
After a quick test, I was able to check that transformations from body inertial to body fixed in poliastro were properly applied (validation was done against GMAT). Regarding, Orekit, output results had the same order of magnitude and sign, but slightly diverged.

This is probably behind the difference in results, see [CelestialBodyFactory docs](https://www.orekit.org/site-orekit-10.2/apidocs/org/orekit/bodies/CelestialBodyFactory.html):

> The underlying body-centered frames are either direct children of EME2000 (for Moon and Earth-Moon barycenter) or children from other body-centered frames. For example, the path from EME2000 to Jupiter-centered frame is: EME2000, Earth-Moon barycenter centered, solar system barycenter centered, Jupiter-centered. The defining transforms of these frames are combinations of simple linear translation/velocity transforms without any rotation. The frame axes are therefore always parallel to EME2000 frame axes.

In addition, the position of the bodies provided by this class are interpolated using the JPL DE 405/DE 406 ephemerides.

**Comment by jorgepiloto** [comment]
The `GCRF` is not the same as `EME2000` in Orekit, as this last frame takes into account Bias.

**Comment by jorgepiloto** [comment]
In poliastro, body inertial frame axes are parallel to those of the ICRS frame for a particular epoch, while in Orekit they are parallel to EME2000. This is probably the reason behind results divergence.

**Comment by jorgepiloto** [comment]
Let me collect inertial frame definitions from each software documentation:

**Celestial bodies inertial frames**

* **poliastro:** frame origin is located in the center of mass of a celestial body, with axes **parallel to those of the ICRS frame** comming from astropy definition. *ICRS is not the same as J2000 frame, although very close*.
* **orekit:** frame origin is located in the center of mass of a celestial body, with axes **parallel to those of the EME2000 (J2000) frame**, [see my previous comment](https://github.com/poliastro/validation/issues/22#issuecomment-782599791).
* **gmat:** different for each body. The x-axis points along the line formed by the intersection of the bodies equator and Earth’s mean equator at J2000. The z-axis points along the body's spin axis direction at the J2000 epoch. The y-axis completes the right-handed set.

**Comment by jorgepiloto** [comment]
This is solved, although some of tests were marked as XFAIL since the rotational elements implemented within Orekit come from the IAU 2009 report, while the poliastro ones do from the 2015 one.

**Comment by astrojuanlu** [comment]
I think we can consider this done! It's the turn for Orekit to update their constants ;)
