### ISSUE TITLE
Add automated quality checks

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/validation#5]
It is unlikely that we will be able to run these tests on CI (or... perhaps not that unlikely?) but regardless, it would be nice to have automated quality checks about PEP8 (preferably flake8 + black).

**Comment by jorgepiloto** [comment]
What about Github actions? Tools like [Miniconda](https://github.com/marketplace/actions/setup-miniconda) or [Anaconda](https://github.com/marketplace/actions/setup-conda) are available, together with [code-quality checkers](https://github.com/marketplace?type=actions&query=python+quality).

These actions can be triggered for particular situations such us new commits in main branch, particular tags... We could start by exploring just the checkers for the moment and see how it performs :thinking:

**Comment by astrojuanlu** [comment]
Yeah, absolutely! GH Actions, Circle CI or Azure Pipelines are all equally valid from my side.

**Comment by jorgepiloto** [comment]
Before closing this: it is possible to trigger the Github actions when a new event takes place in the poliastro's repository (new release, merge into master...). See [workflow-dispatch-events](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#create-a-workflow-dispatch-event).

**Comment by jorgepiloto** [comment]
Ops! Closing this, as CI is already been triggered every time a PR is made or when poliastro merges new code into its main branch.
