### ISSUE TITLE
Ignore orekit-data.zip in VCS

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/validation#8]
In the last merge the `orekit-data.zip` was added to the repository. This file must be removed and the version control system should stop tracking that particular directory.

**Comment by jorgepiloto** [comment]
Solved!

**Comment by astrojuanlu** [comment]
I wonder if we should squash those commits and force push to `master`... I know it's heresy, but it's now or never :/ Those 19 MB will be chasing us forever otherwise.

**Comment by jorgepiloto** [comment]
This was introduced in the following [commit](https://github.com/poliastro/validation/commit/ae73415c29c8524adbb1ffdf573b1897aa28e0cc), my fault.

**Comment by astrojuanlu** [comment]
I reviewed and approved, so it's _our_ fault in any case :)

**Comment by astrojuanlu** [comment]
⚠️ HISTORY HAS BEEN REWRITTEN ⚠️
